# Generated by Django 5.1.13 on 2025-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_studysession"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="total_study_time",
            field=models.IntegerField(default=0),
        ),
    ]
