# Generated by Django 5.1.13 on 2025-12-10 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprogress_completed_at_userprogress_is_completed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gemini_api_key",
                    models.CharField(
                        blank=True,
                        help_text="User's personal Gemini API Key",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("daily_ai_usage_count", models.IntegerField(default=0)),
                (
                    "last_usage_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
