# Generated by Django 5.1.13 on 2026-01-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_subject_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="total_input_tokens",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_output_tokens",
            field=models.BigIntegerField(default=0),
        ),
    ]
