# Generated by Django 5.1.13 on 2026-01-28 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_email_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="_encrypted_api_key",
            field=models.TextField(
                blank=True, db_column="gemini_api_key_encrypted", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gemini_api_key",
            field=models.CharField(
                blank=True,
                help_text="Deprecated - use encrypted key",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AITask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("generate_all", "Generate All Content"),
                            ("generate_notes", "Generate Notes"),
                            ("generate_mindmap", "Generate Mindmap"),
                            ("generate_flashcards", "Generate Flashcards"),
                            ("generate_mcqs", "Generate MCQs"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to="core.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "topic", "task_type"],
                        name="core_aitask_user_id_44cafc_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_aitask_status_b08355_idx"
                    ),
                ],
            },
        ),
    ]
